### ISSUE TITLE
tag repository as iteration 1, push all development code to master, push master to heroku

### ISSUE THREAD

**Issue by baileybauman** [bajabob/Care-Coordinator#49]

**Comment by baileybauman** [comment]
due March 9

**Comment by baileybauman** [comment]
From class website:
Please tag your git repository revision with Iteration1, Iteration2, etc. Here are some example commands for how to tag revisions:

To tag the current revision: git tag -a Iteration1
Warning: You must explicitly push your tags with the command git push --tags. Before you submit, please make sure that when we clone, we can see the tag.

**Comment by bajabob** [comment]
Iteration1 and 0 tagged @baileybauman
